#!/usr/bin/env node
// Part of React Advanced Odontogram - https://github.com/ZoliQua/React-Odontogram-Modul
// Cognovis fork - https://github.com/cognovis/React-Odontogram-Modul
// Dirk Saeger, Malte Sussdorff 2026
//
// Bead odontogram-cpx: provision the scoped odontogram-live Client and
// odontogram-live-dental AccessPolicy against an already-running Reetfurt
// local-UAT instance. Operator credentials stay outside Vite. The browser
// .env receives only the scoped machine client.

import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export const SCOPED_CLIENT_ID = "odontogram-live";
export const SCOPED_POLICY_ID = "odontogram-live-dental";

export const SCOPED_ENV_KEYS = [
  "VITE_AIDBOX_BASE_URL",
  "VITE_AIDBOX_CLIENT_ID",
  "VITE_AIDBOX_CLIENT_SECRET",
  "VITE_DEFAULT_PATIENT_ID",
] as const;

const ADMIN_KEY = /AIDBOX_ADMIN|BOX_ADMIN|VITE_AIDBOX_ADMIN/i;
const HOME_REETFURT_RELATIVE = join("code", "mvz-reetfurt");
const HOME_POLARIS_RELATIVE = join("code", "polaris", "platform");
const POLARIS_OPERATOR_ENV = "packages/pvs-x-isynet/.env";
const DENTAL_OBSERVATION_PROFILE = "https://fhir.cognovis.de/dental-core/StructureDefinition/dental-tooth-state";
const DENTAL_CONDITION_PROFILE = "https://fhir.cognovis.de/dental-core/StructureDefinition/dental-periodontal-diagnosis";

export interface ScopedEnvValues {
  baseUrl: string;
  clientId: string;
  clientSecret: string;
  patientId: string;
}

export interface OperatorCredentials {
  id: string;
  password: string;
}

export interface AidboxClientResource {
  resourceType: "Client";
  id: string;
  secret: string;
  grant_types: string[];
  description: string;
}

export interface AidboxAccessPolicyResource {
  resourceType: "AccessPolicy";
  id: string;
  engine: "matcho";
  description: string;
  link: Array<{ resourceType: string; id: string }>;
  matcho: { "$one-of": Array<Record<string, unknown>> };
}

function cleaned(value: string | undefined): string | undefined {
  const trimmed = typeof value === "string" ? value.trim() : "";
  return trimmed.length > 0 ? trimmed : undefined;
}

function unquote(value: string): string {
  const trimmed = value.trim();
  if ((trimmed.startsWith("\"") && trimmed.endsWith("\"")) || (trimmed.startsWith("'") && trimmed.endsWith("'"))) {
    return trimmed.slice(1, -1);
  }
  return trimmed;
}

export function parseEnvFile(text: string): Record<string, string> {
  const values: Record<string, string> = {};
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const equals = line.indexOf("=");
    if (equals < 1) continue;
    values[line.slice(0, equals)] = unquote(line.slice(equals + 1));
  }
  return values;
}

export function composeScopedEnv(values: ScopedEnvValues): string {
  if (values.clientId !== SCOPED_CLIENT_ID) {
    throw new Error(`Refusing a client id other than ${SCOPED_CLIENT_ID}`);
  }
  return [
    "# Generated by npm run live:provision. Git-ignored. Scoped machine client only.",
    `VITE_AIDBOX_BASE_URL=${values.baseUrl.replace(/\/+$/, "")}`,
    `VITE_AIDBOX_CLIENT_ID=${SCOPED_CLIENT_ID}`,
    `VITE_AIDBOX_CLIENT_SECRET=${values.clientSecret}`,
    `VITE_DEFAULT_PATIENT_ID=${values.patientId}`,
    "",
  ].join("\n");
}

export function writeScopedEnv(target: string, record: Record<string, string>): void {
  const extra = Object.keys(record).filter((key) => !(SCOPED_ENV_KEYS as readonly string[]).includes(key));
  if (extra.length > 0) {
    throw new Error(`Refusing to write operator or extra keys into .env: ${extra.join(", ")}`);
  }
  for (const key of Object.keys(record)) {
    if (ADMIN_KEY.test(key) || key.startsWith("VITE_") && ADMIN_KEY.test(key)) {
      throw new Error(`Refusing to write an admin or operator credential into ${key}`);
    }
  }
  const clientId = cleaned(record.VITE_AIDBOX_CLIENT_ID);
  if (clientId !== SCOPED_CLIENT_ID) {
    throw new Error(`Refusing a scoped .env whose client is not ${SCOPED_CLIENT_ID}`);
  }
  const values: ScopedEnvValues = {
    baseUrl: cleaned(record.VITE_AIDBOX_BASE_URL) ?? "",
    clientId: SCOPED_CLIENT_ID,
    clientSecret: cleaned(record.VITE_AIDBOX_CLIENT_SECRET) ?? "",
    patientId: cleaned(record.VITE_DEFAULT_PATIENT_ID) ?? "",
  };
  if (!values.baseUrl || !values.clientSecret || !values.patientId) {
    throw new Error("Refusing to write an incomplete scoped .env");
  }
  writeFileSync(target, composeScopedEnv(values));
}

export function desiredClient(secret: string): AidboxClientResource {
  if (!cleaned(secret)) throw new Error("A scoped client secret is required");
  return {
    resourceType: "Client",
    id: SCOPED_CLIENT_ID,
    secret,
    grant_types: ["basic"],
    description: "HTTP Basic machine client for the odontogram live-mode browser. Not an administrator.",
  };
}

// Aidbox matcho is conjunctive per object. `$regex` / `$enum` are not this
// server's operators: a `#/pattern` URI is the regex, and `$one-of` is the
// disjunction. Measured against odontogram-cpx: Patient GET 200, Observation
// GET 200, ImplementationGuide GET 403, Patient PUT 403.
export function desiredAccessPolicy(): AidboxAccessPolicyResource {
  return {
    resourceType: "AccessPolicy",
    id: SCOPED_POLICY_ID,
    engine: "matcho",
    description: "odontogram-live: Patient GET only; dental chart resources GET/PUT/POST/DELETE; FHIR only.",
    link: [{ resourceType: "Client", id: SCOPED_CLIENT_ID }],
    matcho: {
      "$one-of": [
        {
          uri: "#/fhir/Patient.*",
          "request-method": "get",
        },
        {
          uri: "#/fhir/(Observation|Condition|ServiceRequest|CarePlan).*",
          "request-method": { "$one-of": ["get", "put", "post", "delete"] },
        },
      ],
    },
  };
}

export function rejectAdminEquivalentClient(client: { grant_types?: unknown; id?: unknown }): void {
  const grants = Array.isArray(client.grant_types) ? client.grant_types.map(String) : [];
  if (grants.includes("client_credentials") || grants.length !== 1 || grants[0] !== "basic") {
    throw new Error(`Refusing an admin-equivalent Aidbox client scope: grant_types=${grants.join(",")}`);
  }
  if (client.id !== SCOPED_CLIENT_ID) {
    throw new Error(`Refusing a client id other than ${SCOPED_CLIENT_ID}`);
  }
}

export function resolveOperatorCredentials(
  env: Record<string, string | undefined>,
  files: string[],
): OperatorCredentials {
  const viteKeys = Object.keys(env).filter((key) => key.startsWith("VITE_") && ADMIN_KEY.test(key));
  if (viteKeys.length > 0) {
    throw new Error(`Operator credentials must not come from VITE_* (${viteKeys.join(", ")})`);
  }
  const fromEnvId = cleaned(env.AIDBOX_ADMIN_ID);
  const fromEnvPassword = cleaned(env.AIDBOX_ADMIN_PASSWORD);
  if (fromEnvId && fromEnvPassword) return { id: fromEnvId, password: fromEnvPassword };

  for (const file of files) {
    if (!existsSync(file)) continue;
    const values = parseEnvFile(readFileSync(file, "utf8"));
    const id = cleaned(values.AIDBOX_ADMIN_ID ?? values.AIDBOX_USER);
    const password = cleaned(values.AIDBOX_ADMIN_PASSWORD ?? values.AIDBOX_PASSWORD);
    if (id && password) return { id, password };
  }
  throw new Error("No Aidbox operator credentials in the environment or PolarIS/Reetfurt operator env file");
}

export function resolveHomeCheckout(
  env: Record<string, string | undefined>,
  envKey: "REETFURT_DIR" | "POLARIS_DIR",
  relativeFromHome: string,
): string {
  const override = cleaned(env[envKey]);
  if (override) return resolve(override);
  const home = cleaned(env.HOME) ?? cleaned(homedir());
  if (!home) {
    throw new Error(`Set ${envKey} to the checkout path, or set HOME so $HOME/${relativeFromHome} can be used`);
  }
  return resolve(join(home, relativeFromHome));
}

export function instanceBindingPath(reetfurtDir: string, instance: string): string {
  return join(reetfurtDir, "build", "local-uat", "dev-instances", instance, "reetfurt.env");
}

export function readInstanceBinding(reetfurtDir: string, instance: string): Record<string, string> {
  const path = instanceBindingPath(reetfurtDir, instance);
  if (!existsSync(path)) {
    throw new Error(
      `Development instance ${instance} has no persisted Reetfurt binding at ${path}; run bun run uat:local up --instance ${instance} first`,
    );
  }
  return parseEnvFile(readFileSync(path, "utf8"));
}

export function parseProvisionArgs(argv: string[]): { instance: string } {
  const instanceFlag = argv.findIndex((arg) => arg === "--instance");
  const instance = instanceFlag >= 0 ? cleaned(argv[instanceFlag + 1]) : undefined;
  if (!instance) {
    throw new Error("Usage: npm run live:provision -- --instance <reetfurt-uat-instance>");
  }
  return { instance };
}

function basicAuthorization(id: string, password: string): string {
  return `Basic ${Buffer.from(`${id}:${password}`, "utf8").toString("base64")}`;
}

async function operatorRequest(
  baseUrl: string,
  credentials: OperatorCredentials,
  method: "GET" | "PUT",
  path: string,
  body?: unknown,
): Promise<{ status: number; resource: unknown }> {
  const url = `${baseUrl.replace(/\/+$/, "")}${path.startsWith("/") ? path : `/${path}`}`;
  const response = await fetch(url, {
    method,
    headers: {
      Authorization: basicAuthorization(credentials.id, credentials.password),
      Accept: "application/json",
      ...(body !== undefined ? { "Content-Type": "application/json" } : {}),
    },
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  const text = await response.text();
  let resource: unknown = null;
  if (text.trim()) {
    try { resource = JSON.parse(text); } catch { resource = text; }
  }
  return { status: response.status, resource };
}

function generateSecret(): string {
  return randomBytes(24).toString("base64url");
}

function subjectPatientId(resource: unknown): string | undefined {
  const reference = (resource as { subject?: { reference?: string } } | null)?.subject?.reference;
  const match = typeof reference === "string" ? reference.match(/^Patient\/([A-Za-z0-9.-]{1,64})$/) : null;
  return match?.[1];
}

async function searchFirst(
  baseUrl: string,
  credentials: OperatorCredentials,
  path: string,
): Promise<unknown | undefined> {
  const result = await operatorRequest(baseUrl, credentials, "GET", path);
  if (result.status !== 200) return undefined;
  const bundle = result.resource as { entry?: Array<{ resource?: unknown }> };
  return bundle.entry?.find((entry) => entry.resource)?.resource;
}

export async function discoverDentalPatient(
  baseUrl: string,
  credentials: OperatorCredentials,
): Promise<string> {
  const fhir = `${baseUrl.replace(/\/+$/, "")}/fhir`;
  const observation = await searchFirst(
    fhir,
    credentials,
    `/Observation?_profile=${encodeURIComponent(DENTAL_OBSERVATION_PROFILE)}&_count=5&_sort=_id`,
  ) ?? await searchFirst(fhir, credentials, "/Observation?_count=20&_sort=_id");
  const condition = observation
    ? undefined
    : await searchFirst(
      fhir,
      credentials,
      `/Condition?_profile=${encodeURIComponent(DENTAL_CONDITION_PROFILE)}&_count=5&_sort=_id`,
    ) ?? await searchFirst(fhir, credentials, "/Condition?_count=20&_sort=_id");
  const patientId = subjectPatientId(observation) ?? subjectPatientId(condition);
  if (!patientId) {
    throw new Error("No Patient with dental Observation or Condition resources in this Reetfurt instance");
  }
  const patient = await operatorRequest(fhir, credentials, "GET", `/Patient/${patientId}`);
  if (patient.status !== 200) {
    throw new Error(`Dental Patient ${patientId} could not be read back from this instance`);
  }
  return patientId;
}

export async function reconcileScopedResources(
  baseUrl: string,
  credentials: OperatorCredentials,
): Promise<{ client: AidboxClientResource; policy: AidboxAccessPolicyResource; createdSecret: boolean }> {
  const fhir = `${baseUrl.replace(/\/+$/, "")}/fhir`;
  const existing = await operatorRequest(fhir, credentials, "GET", `/Client/${SCOPED_CLIENT_ID}`);
  let secret = generateSecret();
  let createdSecret = true;
  if (existing.status === 200) {
    const current = existing.resource as { secret?: string };
    if (cleaned(current.secret)) {
      secret = current.secret as string;
      createdSecret = false;
    }
  }
  const client = desiredClient(secret);
  rejectAdminEquivalentClient(client);
  const writtenClient = await operatorRequest(fhir, credentials, "PUT", `/Client/${SCOPED_CLIENT_ID}`, client);
  if (writtenClient.status >= 300) {
    throw new Error(`PUT Client/${SCOPED_CLIENT_ID} failed: ${writtenClient.status}`);
  }
  const policy = desiredAccessPolicy();
  const writtenPolicy = await operatorRequest(fhir, credentials, "PUT", `/AccessPolicy/${SCOPED_POLICY_ID}`, policy);
  if (writtenPolicy.status >= 300) {
    throw new Error(`PUT AccessPolicy/${SCOPED_POLICY_ID} failed: ${writtenPolicy.status}`);
  }
  return { client, policy, createdSecret };
}

export async function provisionLiveMode(options: {
  instance: string;
  repoRoot: string;
  reetfurtDir?: string;
  polarisDir?: string;
  env?: Record<string, string | undefined>;
}): Promise<{ baseUrl: string; patientId: string; envPath: string }> {
  const env = options.env ?? process.env;
  const reetfurtDir = resolve(options.reetfurtDir ?? resolveHomeCheckout(env, "REETFURT_DIR", HOME_REETFURT_RELATIVE));
  const polarisDir = resolve(options.polarisDir ?? resolveHomeCheckout(env, "POLARIS_DIR", HOME_POLARIS_RELATIVE));
  const binding = readInstanceBinding(reetfurtDir, options.instance);
  const baseUrl = cleaned(binding.POLARIS_AIDBOX_URL);
  if (!baseUrl) {
    throw new Error(`The Reetfurt binding for ${options.instance} names no POLARIS_AIDBOX_URL`);
  }
  const credentials = resolveOperatorCredentials(env, [
    join(polarisDir, POLARIS_OPERATOR_ENV),
    join(reetfurtDir, ".env"),
  ]);
  const { client } = await reconcileScopedResources(baseUrl, credentials);
  const patientId = await discoverDentalPatient(baseUrl, credentials);
  const envPath = join(options.repoRoot, ".env");
  writeScopedEnv(envPath, {
    VITE_AIDBOX_BASE_URL: baseUrl,
    VITE_AIDBOX_CLIENT_ID: SCOPED_CLIENT_ID,
    VITE_AIDBOX_CLIENT_SECRET: client.secret,
    VITE_DEFAULT_PATIENT_ID: patientId,
  });
  return { baseUrl, patientId, envPath };
}

export async function main(argv: string[] = process.argv.slice(2)): Promise<void> {
  const { instance } = parseProvisionArgs(argv);
  const repoRoot = resolve(join(dirname(fileURLToPath(import.meta.url)), ".."));
  const result = await provisionLiveMode({ instance, repoRoot });
  process.stdout.write(
    `Provisioned ${SCOPED_CLIENT_ID} on ${result.baseUrl} for instance ${instance}; patient ${result.patientId}\n`,
  );
}

const invokedDirectly = process.argv[1] !== undefined
  && import.meta.url === pathToFileURL(process.argv[1]).href;

if (invokedDirectly) {
  main().catch((error: unknown) => {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exitCode = 1;
  });
}
